### PR TITLE
update to flyd 0.2

### PR DESCRIPTION
**Pull request by troch**
Added flyd in peer dependencies so people will get an error if trying to use with an incompatible version of Flyd. I also changed the flyd dependency to be `0.2.x` only as it doesn't follow semver.

### CODE REVIEW

**Comment by raine** [comment]
Thank you, Thomas.

**Comment by troch** [comment]
Thanks for your promptness, that's awesome. Just let me know when you publish :)

**Comment by raine** [comment]
There you go.

**Comment by troch** [comment]
:+1: thanks again!

**Pull request merged**
